name: Python API CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest flake8 black coverage

      - name: Run lint
        run: |
          source venv/bin/activate
          flake8 app.py tests/

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --cov=.

      - name: Check code formatting
        run: |
          source venv/bin/activate
          black --check .
    
