name: Python API CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Chekout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: docker build -t calculator-api .

    - name: Run container and test
      run: |
        docker run --rm calculator-api pytest

    - name: Lint with flake9
      run: |
        pip install flake8
        flake8 .
